"""add phone and hired columns

Revision ID: 7c9b8a43a9f0
Revises: 0d5372f2f83a
Create Date: 2025-03-09 22:30:14.512097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9b8a43a9f0'
down_revision: Union[str, None] = '0d5372f2f83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditions', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('auditions', sa.Column('hired', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auditions', 'hired')
    op.drop_column('auditions', 'phone')
    # ### end Alembic commands ###
